const TEMPERAMENT = [
    {temperament:"All", key:1},
    {temperament:"Stubborn", key:2},
    {temperament:"Curious",key:3},
    {temperament:"Playful",key:4},
    {temperament:"Adventurous",key:5},
    {temperament:"Active",key:6},
    {temperament:"Fun-lovi",key:7},
    {temperament:"Aloof",key:8},
    {temperament:"Dignified",key:9},
    {temperament:"Independent",key:10},
    {temperament:"Happy",key:11},
    {temperament:"Wild",key:12},
    {temperament:"Hardworking",key:13},
    {temperament:"Dutiful",key:14},
    {temperament:"Outgoing",key:15},
    {temperament:"Friendly",key:16},
    {temperament:"Alert",key:17},
    {temperament:"Confident",key:18},
    {temperament:"Intelligent",key:19},
    {temperament:"Loyal",key:20},
    {temperament:"Brave",key:21},
    {temperament:"Docile",key:22},
    {temperament:"Responsive",key:23},
    {temperament:"Composed",key:24},
]
export default TEMPERAMENT